---
AWSTemplateFormatVersion: '2010-09-09'

Description: DynamoDB table for ToDo items

Parameters:
  ProjectName:
    Type: String

Resources:
  DeploymentGatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-todos"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
