name: "30 - CI/CD (Deploy App Infra)  📌"

on:
  push:
    branches: [ main ]
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    paths:
      - '.github/actions/**'
      - '.github/workflows/3[0-9]*'
      - '03_app_infra/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    name: Tests
    uses: ./.github/workflows/91-validate-templates.yml
    secrets: inherit
    with:
      working-directory: 03_app_infra

  deploy-develop-account:
    name: Develop
    needs: [ run-tests ]
    uses: ./.github/workflows/31-deploy-cfn-templates.yml
    secrets: inherit
    with:
      stage-env: 'DEVELOP'

  deploy-production-account:
    name: Production
    if: false
    needs: [ deploy-develop-account ]
    uses: ./.github/workflows/31-deploy-cfn-templates.yml
    secrets: inherit
    with:
      stage-env: 'PRODUCTION'
